name: "Test"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: macos-latest
    steps:
    - name: Set all hostname variants
      run: |
        sudo scutil --set HostName "Joaos-MacBook-Pro"
        sudo scutil --set LocalHostName "Joaos-MacBook-Pro"
        sudo scutil --set ComputerName "Joaos-MacBook-Pro"
        # Verify the settings
        echo "HostName: $(scutil --get HostName)"
        echo "LocalHostName: $(scutil --get LocalHostName)"
        echo "ComputerName: $(scutil --get ComputerName)"
        echo "hostname command: $(hostname)"
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run nixpkgs#statix check
    - run: nix run nix-darwin -- build --flake ./
