name: "Test"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: macos-latest
    steps:
    - name: Set hostname
      run: |
        sudo scutil --set LocalHostName "Joaos-MacBook-Pro"
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run github:astro/deadnix -- --fail
    - run: nix run nixpkgs#statix check
    - run: nix run nix-darwin -- build --flake ./
